chat/urls.py
import imp
from django.urls import path

from chat import views

app_name="chat"

urlpatterns = [
    path("chat/index/",views.Index.as_view(),name="index"),
    path("chat/<str:room_name>/",views.Room.as_view(),name="room"),
    path("chat/is_read/<str:room_name>/",views.MessageReadSet.as_view(),name="message"),
    path("chat/is_read/<str:room_name>/sendPhoto/",views.Send_Image,name="send_image"),
    path("chat/<str:room_name>/delete/",views.Delete_Message,name="delete_message"),
 
    
]

chat/models.py
from asyncio.windows_events import NULL
from sqlite3 import Timestamp
from turtle import ondrag
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
# Create your models here.

class Chat(models.Model):
    count = 0

    content = models.CharField(max_length=1555,null=True)
    photo = models.ImageField(upload_to="uploads/message_photos", blank = True, null = True)
    timestamp = models.DateTimeField(auto_now=True)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="+")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="+")
    room = models.ForeignKey('RoomChat',on_delete=models.CASCADE)
    is_read = models.BooleanField(default=False)

    def Counter(self):
        self.count += 1
        return self.count
    

# class Chatroom(models.Model):
#     sender = models.CharField(max_length=55)
#     receiver = models.CharField(max_length=55)
    
class RoomChat(models.Model):
    receiver = models.CharField(max_length=1055)
    sender = models.CharField(max_length=1055)
    sender_profile = models.ForeignKey(User,on_delete=models.CASCADE, related_name="+")
    receiver_profile = models.ForeignKey(User,on_delete=models.CASCADE, related_name="+")
    

class Connected(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="connected")
    room = models.ForeignKey(RoomChat, on_delete=models.CASCADE, related_name="connected")
    channel_name = models.CharField(max_length=100, null=False)
    connect_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

chat/templates/chat/chatlist.html
<!-- chat/templates/chat/index.html -->
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}


{% block body %}
    

    <!-- TODO:Navbar -->
    <div class="fixed top-0 left-0 right-0 z-40 ">
        {% include 'includes/navbar.html' %}
      </div>

    <div class="py-10 h-screen px-2 mt-20">
        <div class="max-w-md mx-auto bg-gray-50 shadow-lg rounded-lg overflow-hidden md:max-w-lg">
            <div class="md:flex">
                <div class="w-full p-4">
                     <div id="search_room" class="mt-2 w-min">
                            <div class="text-sm md:text-lg font-semibold my-0.5 md:my-1 mx-0.5 md:mx-2">Messages</div>
                        </div>
                    <!-- TODO:Displaying ChatList -->
                    {% if chats %}
                        <ul>
                            {% for room in rooms.all %}
                            <li class="flex justify-between items-center shadow-md  mt-2 p-2 bg-gray-50 hover:bg-gray-200 hover:shadow-lg rounded cursor-pointer transition">
                                <div class="flex ml-2 items-center w-full"> 
                                    <!-- <img src="https://i.imgur.com/aq39RMA.jpg" width="40" height="40" class="rounded-full"> -->
                                    <!-- TODO:User image -->
                                    {% if request.user.username == room.sender %}
                                    <a href="{% url 'profiles:user_profile' room.receiver %}" class="object-scale-down ">
                                        {% thumbnail room.receiver_profile.profile.image "45x45" crop="center" as img%}
                                        <img src="{{ img.url }}"
                                            class="object-scale-down rounded-full border-solid border-white border-2 ">
                                        {% endthumbnail %}
        
                                    </a>
                                    {% else %}
                                    <a href="{% url 'profiles:user_profile' room.sender %}" class="object-scale-down ">
                                        {% thumbnail room.sender_profile.profile.image "45x45" crop="center" as img %}
                                        <img src="{{ img.url }}"
                                            class="object-scale-down rounded-full border-solid border-white border-2">
                                        {% endthumbnail %}
        
                                    </a>
                                    {% endif %}
                                    <div class="flex flex-col ml-2 w-full"> 
                                        <!-- <span class="font-medium text-black">Jessica Koel</span>  -->
                                        <!-- TODO:Username -->
                                        {% if request.user.username == room.sender %}
                                            <a href="{% url 'chat:room' room.receiver %}" class="text-decoration-none">
                                                <div class="text-xs  md:text-sm font-semibold overflow-hidden text-gray-700">
                                                    {{room.receiver |capfirst }}</div>
                                            </a>
                                        {% else %}
                                            <a href="{% url 'chat:room' room.sender %}" class="">
                                                <div class="text-xs md:text-sm font-semibold">{{room.sender |capfirst }}</div>
                                            </a>
                                        {% endif %}
                                            <!-- <span class="text-sm text-gray-400 truncate w-32">Hey, Joel, I here to help you out please tell me</span>  -->
                                        <!-- TODO: Chats Message -->
                                        {% for chat in chats %}
    
                                {% if chat.content  %}
    
                                {% if chat.room.id == room.id %}
                                {% if chat.is_read == False %}
                                {% if chat.sender == request.user %}
                                <span
                                    class="text-sm text-gray-400 truncate w-32">{{chat.sender | capfirst}}:{{chat.content}}</span>
                                {% else %}
                                <div
                                    class="text-sm text-gray-400 truncate w-32">{{chat.sender | capfirst}}:<span
                                    class="text-sm font-bold truncate">{{chat.content}}</span></div>
                                {% endif %}
                                {% else %}
                                <div class="text-sm text-gray-400 truncate w-32">{{chat.sender | capfirst}}
                                    : {{chat.content}}</div>
                                {% endif %}
                                {% endif %}
                                {% endif %}
    
                                {% endfor %}

                                    </div>
                                </div>
                                <!-- TODO: Message Time -->
                                {% for chat in chats  %}
                                {% if chat.room.id == room.id %}
                                <div class="flex flex-col my-3 ">
                                    <span class="text-xs text-gray-400 ">{{chat.timestamp | date:"g:i:a"}}</span>
        
        
                                </div>
                                {% endif %}
                                {% endfor %}
                            </li>
                            {% endfor %}
                        </ul>
                        <!-- TODO:If ChatLists are Empty -->
                    {% else %}
                        <ul>
                            <li class="flex justify-between items-center bg-white mt-2 p-2 hover:shadow-lg rounded cursor-pointer transition">
                    
                                        <div class="text-xs md:text-base text-neutral-500 mb-1 md:mb-2">Chat List is Empty</div>
                                        <div class="text-xs md:text-base ">Start Messaging With Your Friends</div>
                                        <div class="text-lg md:text-4xl text-blue-500 text-center"><i class='bx bx-paper-plane'></i></div>
                    
                            </li>
                        </ul>
                        {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock body %}

chat/templates/chat/index.html
<!-- chat/templates/chat/index.html -->
{% load static %}
{% load thumbnail %}

<html>
<body>
    <div id="search_room" class="mt-2 text-xs md:text-lg font-semibold my-0 md:my-1 ml-2 md:ml-4">
        Messages
    </div>
    {% if chats %}
    <div class="w-full overflow-y-scroll">
        <div
            class="flex justify-between items-center m-0.5 md:m-2">
    
            <label for="search" class="sr-only text-xs md:text-sm">Search</label>
            <div class="w-28 sm:w-full  bg-white border rounded-lg md:rounded-full flex justify-between items-center relative mx-1 pl-3  pr-2">
                <input hidden id="room_url" type="text" value="{% url 'feed:search_room' %}">
                <input type="search" name="keyword" id="room-name-input" placeholder="Search"
                    class="text-xs md:text-base w-full outline-none focus:outline-none active:outline-none  "/>
              <button id="room-name-submit" type="button"
                class=" outline-none focus:outline-none active:outline-none self-center">
                <div class="items-center mt-1 ">
                    <i class='bx bx-search-alt-2 text-base md:text-xl'></i>
                </div>
            </button>
           
          </div>
        </div>
    
        {% for room in rooms.all %}



        <div class="mx-auto flex  items-center relative h-auto" x-data="{
                            comment : false,
                        }">


            <div
                class="flex flex-col shadow-md mt-2 py-2 hover:shadow-lg rounded cursor-pointer transition w-full h-full p-0  border bg-gray-50 hover:bg-gray-100 rounded-lg overflow-hidden my-0.5 md:my-1 mx-0.5">
                <div class="flex items-center justify-between self-center ml-1  md:ml-3">
                    <div class="flex items-center mx-0 md:mx-3">
                        <div class="flex w-7 h-7 md:w-10 md:h-10 items-center mx-0 md:mx-1">

                            {% if request.user.username == room.sender %}
                            <a href="{% url 'profiles:user_profile' room.receiver %}" class="object-scale-down ">
                                {% thumbnail room.receiver_profile.profile.image "51x51" crop="center" as img%}
                                <img src="{{ img.url }}"
                                    class="object-scale-down rounded-full border-solid border-white border-2 ">
                                {% endthumbnail %}

                            </a>
                            {% else %}
                            <a href="{% url 'profiles:user_profile' room.sender %}" class="object-scale-down ">
                                {% thumbnail room.sender_profile.profile.image "51x51" crop="center" as img %}
                                <img src="{{ img.url }}"
                                    class="object-scale-down rounded-full border-solid border-white border-2">
                                {% endthumbnail %}

                            </a>
                            {% endif %}

                        </div>
                     
                        <div class="hidden md:flex flex-col w-24 md:w-20 lg:w-40  mx-0.5">
                            {% if request.user.username == room.sender %}
                            <a href="{% url 'chat:room' room.receiver %}" class="stretched-link text-decoration-none">
                                <div class="text-xs  md:text-sm font-semibold overflow-hidden text-gray-700">
                                    {{room.receiver |capfirst }}</div>
                            </a>
                            {% else %}
                            <a href="{% url 'chat:room' room.sender %}" class="stretched-link">
                                <div class="text-xs md:text-sm font-semibold">{{room.sender |capfirst }}</div>
                            </a>
                            {% endif %}


                            {% for chat in chats %}

                            {% if chat.content  %}

                            {% if chat.room.id == room.id %}
                            {% if chat.is_read == False %}
                            {% if chat.sender == request.user %}
                            <span
                                class="text-xs text-gray-600 truncate">{{chat.sender | capfirst}}:{{chat.content}}</span>
                            {% else %}
                            <div
                                class="text-xs md:text-sm text-gray-600 truncate">{{chat.sender | capfirst}}:<span
                                class="text-xs lg:text-sm font-bold truncate">{{chat.content}}</span></div>
                            {% endif %}
                            {% else %}
                            <div class="text-xs text-gray-600 truncate">{{chat.sender | capfirst}}
                                : {{chat.content}}</div>
                            {% endif %}
                            {% endif %}
                            {% endif %}

                            {% endfor %}

                        </div>

                        {% for chat in chats  %}
                        {% if chat.room.id == room.id %}
                        <div class="hidden md:flex flex-col my-3 ">
                            <small class="text-xs text-gray-400 ">{{chat.timestamp | date:"g:i:a"}}</small>


                        </div>
                        {% endif %}
                        {% endfor %}


                    </div>
                </div>
                <!-- TODO:It will display in mobile devices, it will change the appearence of chatrooms in mobile devices -->
                <div class="block md:hidden flex-col w-auto ml-0 md:ml-2 text-center">
                    {% if request.user.username == room.sender %}
                    <a href="{% url 'chat:room' room.receiver %}" class="stretched-link text-decoration-none">
                        <div class="block text-xs  md:text-sm font-semibold overflow-hidden text-gray-700 truncate">
                            {{room.receiver |capfirst }}</div>
                    </a>
                    {% else %}
                    <a href="{% url 'chat:room' room.sender %}" class="stretched-link">
                        <div class="text-xs md:text-sm font-semibold block  truncate"><small>{{room.sender |capfirst }}</small></div>
                    </a>
                    {% endif %}
                </div>
            </div>
            <hr>
        </div>



        {% endfor %}



    </div>

    {% else %}

    <div class="py-10 h-screen bg-gray-300 px-2">
        <div class="max-w-md mx-auto bg-gray-100 shadow-lg rounded-lg overflow-hidden w-full">
            <div class="md:flex">
                <div class="w-full p-1 md:p-4 bg-gray-300">

                    <div class="text-xs md:text-base text-neutral-500 mb-1 md:mb-2">Chat List is Empty</div>
                    <div class="text-xs md:text-base ">Start Messaging With Your Friends</div>
                    <div class="text-lg md:text-4xl text-blue-500 text-center"><i class='bx bx-paper-plane'></i></div>

                </div>
            </div>
        </div>
    </div>
    {% endif %}
</body>

</html>

chat/templates/chat/room.html
<!-- chat/templates/chat/room.html -->
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %}
Chat Room
{% endblock title %}
    
{% block body %}
    {{ room_name|json_script:"room-name" }}
    {{ room.id|json_script:"room_id" }}
    {{ received_user.username|json_script:"received_user" }}
    {{ request.user.username | json_script:"sender" }}
    {{ request.user.id | json_script:"sender_id" }}   
    
<!-- component -->


   

   
<div class="fixed top-0 left-0 right-0 z-40 ">
   {% include 'includes/navbar.html' %}
 </div>



<div class="h-screen bg-gray-300 my-4">
   <div class="flex justify-center items-center bg-white h-screen ">
       <div class="w-4/5 h-fit rounded shadow-2xl">
           <nav class="w-full h-10 bg-gray-300 shadow-lg  rounded-lg rounded-bl-none rounded-br-none flex justify-between items-center">
               <div class="flex justify-center items-center"> <i class="mdi mdi-arrow-left font-normal text-gray-300 ml-1"></i>
                   <!-- <img src="https://i.imgur.com/IAgGUYF.jpg" class="rounded-full ml-1" width="25" height="25">  -->
                   
                   {% thumbnail received_user.profile.image "100x100" crop="center" as img %}
                   <img id="user_dp" src="{{img.url}}" alt="user image"  class="w-8 h-8 rounded-full">
                   {% endthumbnail %}
                   <span class="text-xs md:text-sm font-medium text-gray-700 ml-1 ">{{received_user.username | capfirst }}</span> 
               </div>
               <div class="flex items-center">

                  
                  <button >
                     <i class='mdi mdi-video text-gray-300 hover:text-gray-700 ' ></i>
                  </button>
                  <button >
                     <i class='mdi mdi-dots-vertical text-gray-300 hover:text-gray-700 ' ></i>
                  </button>
               </div>
            
             
                       
           </nav>
   
           <div id="chat-log" class="overflow-auto px-1 py-1" style="height: 24rem;" id="journal-scroll">
               {{ received_user.profile.image.url|json_script:"user_avatar" }}
               <div id="chat_list">

                  
                  {% for chat in  chats %}
                        
                        {% if chat.content %}
                                 
                                 {% ifchanged chat.timestamp.date %}
                                 <div class="flex justify-center"> <span class="text-gray-500 text-xs" style="font-size: 8px;">{{ chat.timestamp | date:"d F y"}}</span> </div>                  
                                 {% endifchanged %}

                                 
                                 {% if chat.sender.id == request.user.id %}

                                 
                                    {% if chat.photo %}
                                          <div class="flex items-end justify-end">
                                             <img id="media_message{{chat.id}}" class="w-22 h-16 md:w-48 md:h-32 justify-end" src="{{chat.photo.url}}" alt="Photo Attachements">
                                          </div>
                                    {% endif %}
                                    <div class="message_btn chat-message mb-1" id="{{chat.id}}">
                                       <div class="flex justify-end pt-2 pl-10"> 
                                          <span id="message_btn{{chat.id}}" class="sender_msg bg-gradient-to-r from-indigo-700 via-indigo-600 to-indigo-800
                                                      h-auto text-white text-xs font-normal p-1 rounded-lg rounded-tr-none px-1 items-end flex justify-end "
                                                style="font-size: 12px;" >
                                             {{chat.content}}
                                             <span class="text-gray-400 pl-1" style="font-size: 8px;">     {% load tz %}
                                                {% timezone "Asia/Kolkata" %}
                                                   {{chat.timestamp | time:"h:i:A"}}
                                                {% endtimezone %}</span>
                                          </span> 
                                       </div>
                                    </div>
                                 
                                 {% else %}
                                       
                                       {% if chat.photo %}
                                          <div class="flex items-end">
                                             <img class="w-22 h-16 md:w-48 md:h-32 items-end" src="{{chat.photo.url}}" alt="Photo Attachements">
                                          </div>
                                       {% endif %}
                                       <div class="chat-message mb-1 my-1">

                                       </div>
                                       <div class="flex items-center pr-10 mt-1"> 
                                          <img src="{{received_user.profile.image.url}}" class="rounded-full shadow-xl" width="15" height="15"> 
                                          
                                          <span class="flex ml-1 h-auto 
                                          bg-gradient-to-r from-purple-900 via-violet-600 to-purple-900
                                          text-white text-xs p-1 font-normal px-1 items-end rounded-lg rounded-bl-none" 
                                             style="font-size: 12px;">
                                             {{chat.content}}
                                             <span class="text-gray-400 pl-1" style="font-size: 8px;">
                                                {% timezone "Asia/Kolkata" %}
                                                {{chat.timestamp | time:"h:i:A"}}
                                             {% endtimezone %}
                                             </span>
                                          </span> 
                                       </div>
                                    
                                 {% endif %}
                                    
                                                            
                        {% endif %}
                                                
                  {% endfor %}
                     
                  
                  
                  
      
                  <div class=" " id="chatmsg"> </div>
               </div>
           </div>
              <!-- Chat Buttons -->
           <div class="flex justify-center items-center p-1 bg-gray-300 shadow-lg rounded-bl-lg rounded-br-lg">
               <div class="relative">
                  <div class="relative"> 
                     <i class="mdi mdi-emoticon-excited-outline absolute top-1 left-1 text-white" style="font-size: 17px !important;font-weight: bold;"></i> 
                     <input  id="chat-message-input" type="text" class="rounded-full pl-6 pr-12 py-2 focus:outline-none h-auto placeholder-gray-100 bg-gray-400 text-white" style="font-size: 11px;width: 225px;" placeholder="Type a message..." id="typemsg"> 
                     <i id="id_image" class="mdi mdi-camera absolute right-2 top-1 text-white"></i>
                   </div>
                  
               
               </div>
              
               <div class="w-7 h-7 rounded-full  bg-gradient-to-r from-purple-900 via-violet-600 to-purple-900 text-center items-center flex justify-center"> 
                  <button id="chat-message-submit" class="w-7 h-7 rounded-full text-center items-center flex justify-center focus:outline-none hover:bg-gray-900 hover:text-white" >
                     <i class="mdi mdi-send  text-white"></i>
                  </button>
                  {{request.user.id|json_script:"user_id"}}
                  {{ room.id | json_script:"room_id" }}
               </div>
               <div id="trash_message" class="hidden w-7 h-7 rounded-full  bg-gradient-to-r from-purple-900 via-violet-600 to-purple-900 text-center items-center flex justify-center"
                    data-message-delete-url="{% url 'chat:delete_message' received_user.username %}"> 
                  <button  class="w-7 h-7 rounded-full text-center items-center flex justify-center focus:outline-none hover:bg-gray-900 hover:text-white" >
                     <i class='bx bx-trash text-gray-100 hover:text-gray-500' ></i>
                  </button>

               </div>
           </div>
       </div>
   </div>
   </div>

        <!-- TODO:Upload Post -->
        <div class="min-w-screen animated fadeIn faster  fixed  left-0 top-0 flex justify-center items-center inset-0 z-40 outline-none focus:outline-none bg-no-repeat bg-center bg-cover hidden js-sendphoto-model"  id="modal-id">
           <div class="absolute bg-black opacity-75 inset-0 z-0 w-100"></div>
           <div class="relative mx-auto my-auto rounded-xl shadow-lg backdrop-opacity-10 backdrop-invert bg-white/30 shadow-lg border backdrop-filter backdrop-blur-xl w-fit h-auto md:w-2/5 p-1 md:p-3 ">
           <!--content-->
             <div class=" m-auto">
             <!--body-->
             <!-- <i class='bx bx-upload text-5xl text-blue-500 text-center'></i> -->
                 <div class="text-center pt-1 md:pt-5  flex-auto justify-center ">
                 
                     <!-- TODO:Add the ajax form -->
   
                       <div class="md:flex-row pt-3 px-0 md:px-3     " style="text-align: -webkit-center;">
                         <div class=" flex flex-col md:flex-row w-3/5 items-baseline "><label  for="id_photo"  class="text-xs md:text-sm text-center text-white">Photo:</label> </div>
                         <input type="file" class="js-send-photo text-center flex flex-col md:flex-row text-xs md:text-sm w-3/5 items-baseline mb-2 text-white" name="photo" required id="id_attachment"></div>
                       <!-- <div id="img-box"  class="w-1/2 h-12 md:h-1/4 md:w-1/2 relative mx-auto"></div> -->
                       <img id="img-send-box"  alt="Upload Photo" class="w-22 h-16 md:w-48 md:h-32 border relative mx-auto ext-xs md:text-sm text-white"></img>
                     
                     <textarea class="js-message-text  text-xs md:text-sm border-2 border-blue-500 mt-2 md:mt-4 w-3/5 h-9 md:h-11"  rows="2" placeholder="Message Text" maxlength="255"  required id="id_text" data-message-url="{% url 'chat:send_image' received_user.username  %} " ></textarea>
                             
                       
                 </div>
             <!--footer-->
                 <div class="  text-center space-x-1 md:block  mt-4">
   
                 <button class="js-send_image  bg-blue-500 text-white font-semibold mb-2 md:mb-0 px-3 py-1 
                               md-py-2 border-b-2 border-green-500 shadow-sm font-medium tracking-wider border 
                               rounded-full hover:shadow-lg hover:bg-gray-100 mr-2 hover:border-green-600 hover:bg-green-500 hover:text-white
                               shadow-md inline-flex text-xs md:text-sm mr-2">
                               Send Message
                 
                 </button>
                 
                   <button class="js-toggle-photo-model-cancel text-xs md:text-sm mb-2 md:mb-0 px-3 py-1 md-py-2  bg-white text-sm shadow-sm font-medium tracking-wider border text-gray-600 rounded-full hover:shadow-lg  ">
                     Cancel
                   </button>
                 </div>
                 <div id="alert-box"></div>
               </div>
           </div>
         </div>



<script>
   
</script>












<!-- Endof Template -->

  
{% endblock body %}